# See: https://github.com/DavidAnson/markdownlint

# Unordered list style
MD004:
  style: dash

MD013:
  line_length: 100
  tables: false # Disable line length for tables

# Ordered list item prefix
MD029:
  style: one_or_ordered

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
